# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='password',
            new_name='passwd',
        ),
    ]
